apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  AUTH_USER: {{ .Values.backend.authUser | default "admin" }}
  AUTH_PASSWORD: {{ .Values.backend.authPassword | default "" }}
  JWT_SECRET: {{ .Values.backend.jwtSecret | default "" }}
